### ISSUE TITLE
Android 8.0 local notification issue.

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#174]
Here's a stackoverflow thread about it:
https://stackoverflow.com/questions/44310130/startservice-throws-java-lang-illegalstateexception

LOG:
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.androidnative.features.notifications.LocalNotificationReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxxxxx.xxxxxxxxx/com.androidnative.features.notifications.LocalNotificationService }: app is in background uid UidRecord{f6f6e86 u0a156 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxxx.xxxxxxxx/com.androidnative.features.notifications.LocalNotificationService }: app is in background uid UidRecord{f6f6e86 u0a156 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.androidnative.features.notifications.LocalNotificationReceiver.onReceive(LocalNotificationReceiver.java:44)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by DonaldQuack** [comment]
duplicate
