### ISSUE TITLE
Error when hiding an application

### ISSUE THREAD

**Issue by Cfyzik** [StansAssets/Development#220]
when I press the home button, sometimes the app crashes with this error. It seems related to the save game that is still in progress but I can't be sure. The save game is usually working fine and I'm connected to Google Play.

I'm on Android 5.0.1, Samsung Galaxy S4, Unity 5.6.3p4, Android Native 9.9/22

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.blueriverarts.evonite, PID: 9307
java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.6.3p4
Device model      : samsung GT-I9505
Device fingerprint: samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHPK2:user/release-keys

Caused by: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
at com.google.android.gms.internal.zzbco.zze(Unknown Source)
at com.google.android.gms.internal.zzbcx.zze(Unknown Source)
at com.google.android.gms.internal.zzbcp.zze(Unknown Source)
at com.google.android.gms.games.internal.api.zzcb.commitAndClose(Unknown Source)
at com.androidnative.gms.listeners.savedgames.SnapshotCreateListner.onResult(SnapshotCreateListner.java:57)
at com.androidnative.gms.listeners.savedgames.SnapshotCreateListner.onResult(SnapshotCreateListner.java:18)
at com.google.android.gms.internal.zzbbg.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5951)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by AlexYaremenko** [comment]
Moved to https://github.com/StansAssets/Development/issues/113
