### ISSUE TITLE
GooglePlayUtils.Instance.GetAdvertisingId on Amazon platform causes app crash

### ISSUE THREAD

**Issue by AlexYaremenko** [StansAssets/Development#78]
Repro Steps:
Required: Amazon Fire Device without Google Play services installed. Device should not have any Google Advertiser Id - which is default in new fire devices. Make sure you don't have Google Play Services installed.
Make a call to get Google advertiser id using following code which should crash the application.

```
GooglePlayUtils.ActionAdvertisingIdLoaded += GoogleAdvertisingIdLoaded;
 GooglePlayUtils.Instance.GetAdvertisingId();  
```

```
02-06 22:47:55.738: E/AndroidRuntime(7106): FATAL EXCEPTION: AsyncTask #1
02-06 22:47:55.738: E/AndroidRuntime(7106): Process: com.madovergames.BubbleShooterWitch.underground, PID: 7106
02-06 22:47:55.738: E/AndroidRuntime(7106): java.lang.Error: FATAL EXCEPTION [AsyncTask #1]
02-06 22:47:55.738: E/AndroidRuntime(7106): Unity version     : 5.4.2f1
02-06 22:47:55.738: E/AndroidRuntime(7106): Device model      : Amazon KFARWI
02-06 22:47:55.738: E/AndroidRuntime(7106): Device fingerprint: Amazon/full_ariel/ariel:5.1.1/LVY48F/20.5.5.4_user_554207020:user/release-keys
02-06 22:47:55.738: E/AndroidRuntime(7106): Caused by: java.lang.RuntimeException: An error occured while executing doInBackground()
02-06 22:47:55.738: E/AndroidRuntime(7106):     at android.os.AsyncTask$3.done(AsyncTask.java:304)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.lang.Thread.run(Thread.java:818)
02-06 22:47:55.738: E/AndroidRuntime(7106): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.ads.identifier.AdvertisingIdClient$Info.getId()' on a null object reference
02-06 22:47:55.738: E/AndroidRuntime(7106):     at com.androidnative.gms.utils.PS_Utility$1.doInBackground(PS_Utility.java:35)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at com.androidnative.gms.utils.PS_Utility$1.doInBackground(PS_Utility.java:23)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at android.os.AsyncTask$2.call(AsyncTask.java:292)
02-06 22:47:55.738: E/AndroidRuntime(7106):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-06 22:47:55.738: E/AndroidRuntime(7106):     ... 4 more
```

Proposed Solution: 
Simply add the null check and expect your code to work on devices without Google Play Services installed:

```
02-06 22:47:55.738: E/AndroidRuntime(7106): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.ads.identifier.AdvertisingIdClient$Info.getId()' on a null object reference
02-06 22:47:55.738: E/AndroidRuntime(7106):     at com.androidnative.gms.utils.PS_Utility$1.doInBackground(PS_Utility.java:35)
02-06 22:47:55.738: E/AndroidRuntime(7106): 
```

**Comment by AlexYaremenko** [comment]
Fixed
