### ISSUE TITLE
Android println needs a message

### ISSUE THREAD

**Issue by frosting17** [StansAssets/Development#85]
java.lang.NullPointerException: println needs a message
    at android.util.Log.println_native(Native Method)
    at android.util.Log.d(Log.java:158)
    at com.androidnative.gcm.GcmIntentService.sendNotification(GcmIntentService.java:295)
    at com.androidnative.gcm.GcmIntentService.onHandleIntent(GcmIntentService.java:97)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by AlexYaremenko** [comment]
Fixed!
